name: Bug report
description: Report a bug to help us improve
title: '[Bug] '
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        ↑ Please have a brief description about the bug in the title
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug in detail
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduce steps
      description: Describe how to reproduce the bug
  - type: dropdown
    id: platform
    attributes:
      label: Server platform
      options:
        - Bukkit
        - Spigot
        - Paper
        - Folia
        - Fabric
        - Forge
        - Neoforge
    validations:
      required: true
  - type: input
    id: mcversion
    attributes:
      label: Minecraft version
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: OPanel version
      description: OPanel version can be found at the about page or in the name of the jar file
    validations:
      required: true
  - type: checkboxes
    id: checkagain
    attributes:
      label: Please check the following
      description: |
        1. **I've read the [docs](https://opanel.cn/en/docs/quick-start.html) and [FAQ](https://opanel.cn/en/docs/faq.html)**
        2. I'm sure this issue has NOT been reported before
      options:
        - label: I checked
          required: true
