name: OPanel
version: ${version}
main: net.opanel.spigot_1_16_1.Main
description: A Minecraft server management panel
author: NriotHrreion
website: https://opanel.cn
api-version: '${api_version}'

commands:
  opanel:
    description: Get status or about info of OPanel
    usage: /opanel [about|status|start|stop]
    permission: opanel.command.opanel
